services:
  ms-avis:
    image: ms-avis:latest
    container_name: ms-avis
    ports:
      - "8000:8000"
    networks:
    - mern-network

networks:
  mern-network:
    external: true
    name: mern-network