services:

  front-avis:
    image: front-avis:latest
    container_name: front-avis
    ports:
      - "90:80"
    networks:
      - mern-network

networks:
  mern-network:
    external: true
    name: mern-network