apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-mongodb-deployment
spec:
  selector:
    matchLabels:
      app: mern-mongodb
  template:
    metadata:
      labels:
        app: mern-mongodb
    spec:
      containers:
      - name: mern-mongodb
        image: mongo:4-focal
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mern-mongodb-service
spec:
  selector:
    app: mern-mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
