apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-mongodb-express-deployment
spec:
  selector:
    matchLabels:
      app: mern-mongodb-express
  template:
    metadata:
      labels:
        app: mern-mongodb-express
    spec:
      containers:
      - name: mern-mongodb-express
        image: mongo-express:1-18-alpine3.18
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: mern-mongodb-express-service
spec:
  #type: NodePort 
  selector:
    app: mern-mongodb-express
  ports:
  - port: 8081
    targetPort: 8081
    #nodePort: 30000
